[package]
name = "defined-terms-parity"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
legal-structure = { git = "https://github.com/eliziff/legal-structure.git", rev = "46e23615828d9cdd00578de2172f6dd2ff568ad7" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
