"""Cross-runtime grammar tables, Python side.

Contract (mirrored by Beaver's experimental TypeScript adapter): patterns
are authored in JS syntax; this loader translates named groups
((?<name>...) -> (?P<name>...)) and compiles with re.ASCII, while
\\s \\S \\w \\W \\b \\B are expanded at compile time to explicit
constructs frozen from the Unicode semantics the source grammars were
battle-tested under (JS and Python native semantics diverge three ways
on NBSP-bearing and accented text; measured, 62 + 242 findings before
the expansions). \\d stays ASCII deliberately. The validator bans the
constructs that genuinely diverge. Lookbehind is allowed: re only
compiles the fixed-width form, where JS semantics coincide, so this
loader's compile step IS the gate. Tables may carry `defs`, named
fragments spliced in via {{name}} before validation and compilation.
`python -X utf8 -m legalpdf.grammar_tables --check <corpus>` runs every
vector of every table and exits nonzero on any failure.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

GRAMMAR_CORPUS_FORMAT = "legal-grammar-corpus:v1"
VENDORED_CORPUS = (
    Path(__file__).resolve().parents[2]
    / "data"
    / "legal-grammar-tables"
    / "grammar-corpus.json"
)

_NAMED_GROUP = re.compile(r"\(\?<([A-Za-z_][A-Za-z0-9_]*)>")
_DEF_REF = re.compile(r"\{\{([A-Za-z_][A-Za-z0-9_]*)\}\}")
_FLAG_BITS = {"i": re.IGNORECASE, "m": re.MULTILINE, "s": re.DOTALL}

# The whitespace set Python's Unicode \s matched when the source grammars
# were battle-tested (NBSP and \x1c-\x1f yes, U+FEFF no). Both loaders
# expand \s/\S to this class so JS (whose \s is Unicode-ish in every
# mode) and Python-with-re.ASCII reproduce the source behavior exactly.
SOURCE_WHITESPACE = (
    r" \t\n\r\f\v\x1c-\x1f\x85\u00a0\u1680"
    r"\u2000-\u200a\u2028\u2029\u202f\u205f\u3000"
)


# The BMP word class Python's Unicode \w matched when the source
# grammars were battle-tested. Generated by tools/gen_word_class.py
# (python 3.11.15, unicodedata 14.0.0) and FROZEN — regenerating
# changes match behavior and needs the full differential + FR gates.
# Do not hand-edit.
SOURCE_WORD = "0-9A-Z_a-z\\u00aa\\u00b2\\u00b3\\u00b5\\u00b9\\u00ba\\u00bc-\\u00be\\u00c0-\\u00d6\\u00d8-\\u00f6\\u00f8-\\u02c1\\u02c6-\\u02d1\\u02e0-\\u02e4\\u02ec\\u02ee\\u0370-\\u0374\\u0376\\u0377\\u037a-\\u037d\\u037f\\u0386\\u0388-\\u038a\\u038c\\u038e-\\u03a1\\u03a3-\\u03f5\\u03f7-\\u0481\\u048a-\\u052f\\u0531-\\u0556\\u0559\\u0560-\\u0588\\u05d0-\\u05ea\\u05ef-\\u05f2\\u0620-\\u064a\\u0660-\\u0669\\u066e\\u066f\\u0671-\\u06d3\\u06d5\\u06e5\\u06e6\\u06ee-\\u06fc\\u06ff\\u0710\\u0712-\\u072f\\u074d-\\u07a5\\u07b1\\u07c0-\\u07ea\\u07f4\\u07f5\\u07fa\\u0800-\\u0815\\u081a\\u0824\\u0828\\u0840-\\u0858\\u0860-\\u086a\\u0870-\\u0887\\u0889-\\u088e\\u08a0-\\u08c9\\u0904-\\u0939\\u093d\\u0950\\u0958-\\u0961\\u0966-\\u096f\\u0971-\\u0980\\u0985-\\u098c\\u098f\\u0990\\u0993-\\u09a8\\u09aa-\\u09b0\\u09b2\\u09b6-\\u09b9\\u09bd\\u09ce\\u09dc\\u09dd\\u09df-\\u09e1\\u09e6-\\u09f1\\u09f4-\\u09f9\\u09fc\\u0a05-\\u0a0a\\u0a0f\\u0a10\\u0a13-\\u0a28\\u0a2a-\\u0a30\\u0a32\\u0a33\\u0a35\\u0a36\\u0a38\\u0a39\\u0a59-\\u0a5c\\u0a5e\\u0a66-\\u0a6f\\u0a72-\\u0a74\\u0a85-\\u0a8d\\u0a8f-\\u0a91\\u0a93-\\u0aa8\\u0aaa-\\u0ab0\\u0ab2\\u0ab3\\u0ab5-\\u0ab9\\u0abd\\u0ad0\\u0ae0\\u0ae1\\u0ae6-\\u0aef\\u0af9\\u0b05-\\u0b0c\\u0b0f\\u0b10\\u0b13-\\u0b28\\u0b2a-\\u0b30\\u0b32\\u0b33\\u0b35-\\u0b39\\u0b3d\\u0b5c\\u0b5d\\u0b5f-\\u0b61\\u0b66-\\u0b6f\\u0b71-\\u0b77\\u0b83\\u0b85-\\u0b8a\\u0b8e-\\u0b90\\u0b92-\\u0b95\\u0b99\\u0b9a\\u0b9c\\u0b9e\\u0b9f\\u0ba3\\u0ba4\\u0ba8-\\u0baa\\u0bae-\\u0bb9\\u0bd0\\u0be6-\\u0bf2\\u0c05-\\u0c0c\\u0c0e-\\u0c10\\u0c12-\\u0c28\\u0c2a-\\u0c39\\u0c3d\\u0c58-\\u0c5a\\u0c5d\\u0c60\\u0c61\\u0c66-\\u0c6f\\u0c78-\\u0c7e\\u0c80\\u0c85-\\u0c8c\\u0c8e-\\u0c90\\u0c92-\\u0ca8\\u0caa-\\u0cb3\\u0cb5-\\u0cb9\\u0cbd\\u0cdd\\u0cde\\u0ce0\\u0ce1\\u0ce6-\\u0cef\\u0cf1\\u0cf2\\u0d04-\\u0d0c\\u0d0e-\\u0d10\\u0d12-\\u0d3a\\u0d3d\\u0d4e\\u0d54-\\u0d56\\u0d58-\\u0d61\\u0d66-\\u0d78\\u0d7a-\\u0d7f\\u0d85-\\u0d96\\u0d9a-\\u0db1\\u0db3-\\u0dbb\\u0dbd\\u0dc0-\\u0dc6\\u0de6-\\u0def\\u0e01-\\u0e30\\u0e32\\u0e33\\u0e40-\\u0e46\\u0e50-\\u0e59\\u0e81\\u0e82\\u0e84\\u0e86-\\u0e8a\\u0e8c-\\u0ea3\\u0ea5\\u0ea7-\\u0eb0\\u0eb2\\u0eb3\\u0ebd\\u0ec0-\\u0ec4\\u0ec6\\u0ed0-\\u0ed9\\u0edc-\\u0edf\\u0f00\\u0f20-\\u0f33\\u0f40-\\u0f47\\u0f49-\\u0f6c\\u0f88-\\u0f8c\\u1000-\\u102a\\u103f-\\u1049\\u1050-\\u1055\\u105a-\\u105d\\u1061\\u1065\\u1066\\u106e-\\u1070\\u1075-\\u1081\\u108e\\u1090-\\u1099\\u10a0-\\u10c5\\u10c7\\u10cd\\u10d0-\\u10fa\\u10fc-\\u1248\\u124a-\\u124d\\u1250-\\u1256\\u1258\\u125a-\\u125d\\u1260-\\u1288\\u128a-\\u128d\\u1290-\\u12b0\\u12b2-\\u12b5\\u12b8-\\u12be\\u12c0\\u12c2-\\u12c5\\u12c8-\\u12d6\\u12d8-\\u1310\\u1312-\\u1315\\u1318-\\u135a\\u1369-\\u137c\\u1380-\\u138f\\u13a0-\\u13f5\\u13f8-\\u13fd\\u1401-\\u166c\\u166f-\\u167f\\u1681-\\u169a\\u16a0-\\u16ea\\u16ee-\\u16f8\\u1700-\\u1711\\u171f-\\u1731\\u1740-\\u1751\\u1760-\\u176c\\u176e-\\u1770\\u1780-\\u17b3\\u17d7\\u17dc\\u17e0-\\u17e9\\u17f0-\\u17f9\\u1810-\\u1819\\u1820-\\u1878\\u1880-\\u1884\\u1887-\\u18a8\\u18aa\\u18b0-\\u18f5\\u1900-\\u191e\\u1946-\\u196d\\u1970-\\u1974\\u1980-\\u19ab\\u19b0-\\u19c9\\u19d0-\\u19da\\u1a00-\\u1a16\\u1a20-\\u1a54\\u1a80-\\u1a89\\u1a90-\\u1a99\\u1aa7\\u1b05-\\u1b33\\u1b45-\\u1b4c\\u1b50-\\u1b59\\u1b83-\\u1ba0\\u1bae-\\u1be5\\u1c00-\\u1c23\\u1c40-\\u1c49\\u1c4d-\\u1c7d\\u1c80-\\u1c88\\u1c90-\\u1cba\\u1cbd-\\u1cbf\\u1ce9-\\u1cec\\u1cee-\\u1cf3\\u1cf5\\u1cf6\\u1cfa\\u1d00-\\u1dbf\\u1e00-\\u1f15\\u1f18-\\u1f1d\\u1f20-\\u1f45\\u1f48-\\u1f4d\\u1f50-\\u1f57\\u1f59\\u1f5b\\u1f5d\\u1f5f-\\u1f7d\\u1f80-\\u1fb4\\u1fb6-\\u1fbc\\u1fbe\\u1fc2-\\u1fc4\\u1fc6-\\u1fcc\\u1fd0-\\u1fd3\\u1fd6-\\u1fdb\\u1fe0-\\u1fec\\u1ff2-\\u1ff4\\u1ff6-\\u1ffc\\u2070\\u2071\\u2074-\\u2079\\u207f-\\u2089\\u2090-\\u209c\\u2102\\u2107\\u210a-\\u2113\\u2115\\u2119-\\u211d\\u2124\\u2126\\u2128\\u212a-\\u212d\\u212f-\\u2139\\u213c-\\u213f\\u2145-\\u2149\\u214e\\u2150-\\u2189\\u2460-\\u249b\\u24ea-\\u24ff\\u2776-\\u2793\\u2c00-\\u2ce4\\u2ceb-\\u2cee\\u2cf2\\u2cf3\\u2cfd\\u2d00-\\u2d25\\u2d27\\u2d2d\\u2d30-\\u2d67\\u2d6f\\u2d80-\\u2d96\\u2da0-\\u2da6\\u2da8-\\u2dae\\u2db0-\\u2db6\\u2db8-\\u2dbe\\u2dc0-\\u2dc6\\u2dc8-\\u2dce\\u2dd0-\\u2dd6\\u2dd8-\\u2dde\\u2e2f\\u3005-\\u3007\\u3021-\\u3029\\u3031-\\u3035\\u3038-\\u303c\\u3041-\\u3096\\u309d-\\u309f\\u30a1-\\u30fa\\u30fc-\\u30ff\\u3105-\\u312f\\u3131-\\u318e\\u3192-\\u3195\\u31a0-\\u31bf\\u31f0-\\u31ff\\u3220-\\u3229\\u3248-\\u324f\\u3251-\\u325f\\u3280-\\u3289\\u32b1-\\u32bf\\u3400-\\u4dbf\\u4e00-\\ua48c\\ua4d0-\\ua4fd\\ua500-\\ua60c\\ua610-\\ua62b\\ua640-\\ua66e\\ua67f-\\ua69d\\ua6a0-\\ua6ef\\ua717-\\ua71f\\ua722-\\ua788\\ua78b-\\ua7ca\\ua7d0\\ua7d1\\ua7d3\\ua7d5-\\ua7d9\\ua7f2-\\ua801\\ua803-\\ua805\\ua807-\\ua80a\\ua80c-\\ua822\\ua830-\\ua835\\ua840-\\ua873\\ua882-\\ua8b3\\ua8d0-\\ua8d9\\ua8f2-\\ua8f7\\ua8fb\\ua8fd\\ua8fe\\ua900-\\ua925\\ua930-\\ua946\\ua960-\\ua97c\\ua984-\\ua9b2\\ua9cf-\\ua9d9\\ua9e0-\\ua9e4\\ua9e6-\\ua9fe\\uaa00-\\uaa28\\uaa40-\\uaa42\\uaa44-\\uaa4b\\uaa50-\\uaa59\\uaa60-\\uaa76\\uaa7a\\uaa7e-\\uaaaf\\uaab1\\uaab5\\uaab6\\uaab9-\\uaabd\\uaac0\\uaac2\\uaadb-\\uaadd\\uaae0-\\uaaea\\uaaf2-\\uaaf4\\uab01-\\uab06\\uab09-\\uab0e\\uab11-\\uab16\\uab20-\\uab26\\uab28-\\uab2e\\uab30-\\uab5a\\uab5c-\\uab69\\uab70-\\uabe2\\uabf0-\\uabf9\\uac00-\\ud7a3\\ud7b0-\\ud7c6\\ud7cb-\\ud7fb\\uf900-\\ufa6d\\ufa70-\\ufad9\\ufb00-\\ufb06\\ufb13-\\ufb17\\ufb1d\\ufb1f-\\ufb28\\ufb2a-\\ufb36\\ufb38-\\ufb3c\\ufb3e\\ufb40\\ufb41\\ufb43\\ufb44\\ufb46-\\ufbb1\\ufbd3-\\ufd3d\\ufd50-\\ufd8f\\ufd92-\\ufdc7\\ufdf0-\\ufdfb\\ufe70-\\ufe74\\ufe76-\\ufefc\\uff10-\\uff19\\uff21-\\uff3a\\uff41-\\uff5a\\uff66-\\uffbe\\uffc2-\\uffc7\\uffca-\\uffcf\\uffd2-\\uffd7\\uffda-\\uffdc"

WORD_BOUNDARY = (
    f"(?:(?<![{SOURCE_WORD}])(?=[{SOURCE_WORD}])"
    f"|(?<=[{SOURCE_WORD}])(?![{SOURCE_WORD}]))"
)
WORD_NONBOUNDARY = (
    f"(?:(?<=[{SOURCE_WORD}])(?=[{SOURCE_WORD}])"
    f"|(?<![{SOURCE_WORD}])(?![{SOURCE_WORD}]))"
)


def expand_portable(source: str) -> str:
    """\\s \\S \\w \\W \\b \\B -> explicit source-semantics constructs.

    Mirrors the TS walk exactly: inside a class \\s/\\w become bare
    fragments and \\b stays (backspace); \\S/\\W/\\B inside a class
    raise; outside, \\b/\\B become the lookaround pair over the source
    word class.
    """
    out: list[str] = []
    in_class = False
    i = 0
    while i < len(source):
        ch = source[i]
        if ch == "\\" and i + 1 < len(source):
            nxt = source[i + 1]
            if nxt == "s":
                out.append(SOURCE_WHITESPACE if in_class else f"[{SOURCE_WHITESPACE}]")
                i += 2
                continue
            if nxt == "w":
                out.append(SOURCE_WORD if in_class else f"[{SOURCE_WORD}]")
                i += 2
                continue
            if nxt in ("S", "W"):
                if in_class:
                    raise ValueError(
                        f"\\{nxt} inside a character class cannot be expanded portably"
                    )
                frag = SOURCE_WHITESPACE if nxt == "S" else SOURCE_WORD
                out.append(f"[^{frag}]")
                i += 2
                continue
            if nxt == "b" and not in_class:
                out.append(WORD_BOUNDARY)
                i += 2
                continue
            if nxt == "B":
                if in_class:
                    raise ValueError(
                        "\\B inside a character class cannot be expanded portably"
                    )
                out.append(WORD_NONBOUNDARY)
                i += 2
                continue
            out.append(ch + nxt)
            i += 2
            continue
        if ch == "[" and not in_class:
            in_class = True
        elif ch == "]" and in_class:
            in_class = False
        out.append(ch)
        i += 1
    return "".join(out)


def expand_pattern(source: str, defs: dict[str, str] | None = None) -> str:
    """{{name}} splicing to a fixpoint; must match the TS expansion."""
    table = defs or {}
    out = source
    for _ in range(11):
        def _sub(match: re.Match[str]) -> str:
            name = match.group(1)
            if name not in table:
                raise KeyError(f"grammar def {{{{{name}}}}} is not defined")
            return table[name]

        nxt = _DEF_REF.sub(_sub, out)
        if nxt == out:
            return out
        out = nxt
    raise ValueError("grammar defs reference each other in a cycle")


def validate_pattern(source: str) -> list[str]:
    violations: list[str] = []
    if "(?P" in source:
        violations.append("(?P named-group syntax: author JS-style (?<name>...)")
    if re.search(r"\\[pP]\{", source):
        violations.append("\\p{...} classes: unsupported in re")
    for match in re.finditer(r"\(\?([a-zA-Z-]+)[:)]", source):
        violations.append(f"inline flags (?{match.group(1)}...: banned")
    if re.search(r"(?:^|[^\\])\(\?\(", source):
        # \(? followed by a group is not a conditional; require the opening
        # paren to be unescaped, mirroring the TS validator.
        violations.append("conditional groups: not portable")
    if re.search(r"\\u\{", source):
        violations.append("braced \\u{...} escape: JS-only; use \\uXXXX or the literal")
    return violations


def compile_entry(entry: dict, defs: dict[str, str] | None = None) -> re.Pattern[str]:
    expanded = expand_portable(expand_pattern(entry["pattern"], defs))
    source = _NAMED_GROUP.sub(r"(?P<\1>", expanded)
    flags = re.ASCII
    for ch in entry.get("flags", ""):
        flags |= _FLAG_BITS[ch]
    return re.compile(source, flags)


def canonicalize(groups: dict, rules: dict) -> dict:
    out = dict(groups)
    for name in rules.get("lowercase", []):
        if name in out and out[name] is not None:
            out[name] = out[name].lower()
    for name, chars in rules.get("strip", {}).items():
        if name in out and out[name] is not None:
            out[name] = "".join(ch for ch in out[name] if ch not in chars)
    for name, mapping in rules.get("map", {}).items():
        if name in out and out[name] in mapping:
            out[name] = mapping[out[name]]
    return out


def run_vectors(table: dict) -> list[str]:
    failures: list[str] = []
    defs = table.get("defs") or {}
    for entry in table.get("entries", []):
        eid = entry.get("id", "?")
        try:
            expanded = expand_pattern(entry["pattern"], defs)
        except (KeyError, ValueError) as error:
            failures.append(f"{eid}: {error}")
            continue
        for violation in validate_pattern(expanded):
            failures.append(f"{eid}: {violation}")
        if not re.fullmatch(r"[ims]*", entry.get("flags", "")):
            failures.append(f'{eid}: flags must be a subset of "ims"')
        try:
            pattern = compile_entry(entry, defs)
        except re.error as error:
            failures.append(f"{eid}: does not compile in Python: {error}")
            continue
        for vector in entry.get("vectors", []):
            match = pattern.search(vector["input"])
            expected = vector["groups"]
            if expected is None:
                if match:
                    failures.append(
                        f'{eid}: "{vector["input"]}" expected no match, got "{match.group(0)}"'
                    )
                continue
            if not match:
                failures.append(f'{eid}: "{vector["input"]}" expected a match, got none')
                continue
            got = match.groupdict()
            for name, value in expected.items():
                if got.get(name) != value:
                    failures.append(
                        f'{eid}: "{vector["input"]}" group {name}: expected "{value}", got "{got.get(name)}"'
                    )
            if vector.get("canonical"):
                canon = canonicalize(got, entry.get("canonical", {}))
                for name, value in vector["canonical"].items():
                    if canon.get(name) != value:
                        failures.append(
                            f'{eid}: "{vector["input"]}" canonical {name}: expected "{value}", got "{canon.get(name)}"'
                        )
    return failures


def read_corpus(path: Path) -> dict:
    corpus_path = path / "grammar-corpus.json" if path.is_dir() else path
    corpus = json.loads(corpus_path.read_text(encoding="utf-8"))
    if corpus.get("format") != GRAMMAR_CORPUS_FORMAT:
        raise ValueError(
            f"{corpus_path}: unexpected format {corpus.get('format')!r}"
        )
    tables = corpus.get("tables")
    if not isinstance(tables, dict) or not tables:
        raise ValueError(f"{corpus_path}: missing tables")
    return tables


def check_corpus(path: Path) -> int:
    try:
        table_values = read_corpus(path)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(error, file=sys.stderr)
        return 2
    failed = 0
    for name, table in sorted(table_values.items()):
        failures = run_vectors(table)
        entries = len(table.get("entries", []))
        vectors = sum(len(e.get("vectors", [])) for e in table.get("entries", []))
        if failures:
            failed += 1
            print(f"{name}: FAIL ({entries} entries, {vectors} vectors)")
            for failure in failures:
                print(f"  {failure}")
        else:
            print(f"{name}: ok ({entries} entries, {vectors} vectors)")
    return 1 if failed else 0


def load_tables() -> dict[str, tuple[dict, dict]]:
    """Return every entry from the bundled grammar corpus."""
    tables: dict[str, tuple[dict, dict]] = {}
    for name, table in read_corpus(VENDORED_CORPUS).items():
        defs = table.get("defs") or {}
        for entry in table.get("entries", []):
            entry_id = entry["id"]
            if entry_id in tables:
                raise ValueError(f"{name}: duplicate grammar entry id {entry_id!r}")
            tables[entry_id] = (entry, defs)
    return tables


_DEFAULT_TABLES: dict[str, tuple[dict, dict]] | None = None


def compile_table_entry(
    entry_id: str, tables: dict[str, tuple[dict, dict]] | None = None
) -> re.Pattern[str]:
    """Compile one entry by id; the default tables are loaded once per process."""
    global _DEFAULT_TABLES
    if tables is None:
        if _DEFAULT_TABLES is None:
            _DEFAULT_TABLES = load_tables()
        tables = _DEFAULT_TABLES
    entry, defs = tables[entry_id]
    return compile_entry(entry, defs)


class _LazyTableEntry:
    """A table entry that compiles on first use and then acts as its pattern.

    Boundary expansion makes the compiled tables expensive (~1.8s cold for
    the 26 splitter entries), so modules that bind many of these at import
    must not pay that up front. Method and attribute access delegates to
    the compiled re.Pattern; the __class__ property keeps
    isinstance(x, re.Pattern) probes (tools/grammar_differential.py)
    truthful about what callers receive.
    """

    __slots__ = ("_entry_id", "_pattern")

    def __init__(self, entry_id: str) -> None:
        self._entry_id = entry_id
        self._pattern: re.Pattern[str] | None = None

    @property
    def __class__(self):  # noqa: D105 - deliberate re.Pattern impersonation
        return re.Pattern

    def __getattr__(self, name: str):
        if self._pattern is None:
            self._pattern = compile_table_entry(self._entry_id)
        return getattr(self._pattern, name)


def lazy_table_entry(entry_id: str) -> re.Pattern[str]:
    """A re.Pattern-shaped handle on one table entry, compiled at first use."""
    return _LazyTableEntry(entry_id)  # type: ignore[return-value]


if __name__ == "__main__":
    args = sys.argv[1:]
    if len(args) == 2 and args[0] == "--check":
        raise SystemExit(check_corpus(Path(args[1])))
    print("usage: python -m legalpdf.grammar_tables --check <corpus>", file=sys.stderr)
    raise SystemExit(2)
